version: "3.7"
services: 
  app:
    build: .
    volumes: 
      - .:/app
    working_dir: /app
    ports: 
      - ${NODE_PORT}:${NODE_PORT}
    environment: 
      - MESSAGE=COMPOSE VIEW
    command: yarn start